const SHAKE_STEPS = [
  { icon: "tap", title: "Pick a protein shake", body: "Tap a protein shake on the machine's screen." },
  { icon: "qr", title: "Pay with UPI", body: "Scan the QR on its pay screen with any UPI app." },
  { icon: "cup", title: "Get your protein shake", body: "The machine makes your protein shake as soon as you've paid." },
];

export const DRINKS_COPY = {
  badge: "Buying on your phone is coming soon",
  titleLead: "Protein shakes",
  titleHighlight: "on the machine.",
  lead: "Soon you'll pick a protein shake here, pay on your phone and get a code to type on the machine. For now, buy on the machine's screen.",
  buyCta: "How to buy",
  menuCta: "See the menu",
  quickStats: [
    { val: "UPI", label: "any app" },
    { val: "60s", label: "blend time" },
    { val: "12", label: "blends" },
  ],
  blendChip: { label: "Blend time", value: "60s" },
  codeChip: { title: "Have a code?", body: "Tap Get Drinks on the machine and type it in." },
  stepsEyebrow: "Buying today",
  stepsTitleLead: "Buy on the machine.",
  stepsTitleHighlight: "Pay with any UPI app.",
  stepsLead: "It takes about a minute and you don't need an account.",
  steps: SHAKE_STEPS,
  codeEyebrow: "Got a code?",
  codeTitleLead: "Type it in.",
  codeTitleHighlight: "No payment needed.",
  codeLead: "If your gym or MuscleBoxPro gave you a code, use it on the machine instead of paying.",
  codeSteps: [
    { icon: "tap", title: "Tap Get Drinks", body: "Find the Get Drinks button on the machine's screen." },
    { icon: "code", title: "Type your code", body: "Enter the code exactly as you got it." },
    { icon: "cup", title: "Get your protein shake", body: "The machine makes your protein shake straight away." },
  ],
  joinTitleLead: "Every 10th protein shake",
  joinTitleHighlight: "is free.",
  joinLead: "Member accounts are coming soon. Sign in with your email and every protein shake you buy on your phone earns a stamp.",
  joinCta: "See how it works",
  menuLink: "See every protein shake we make",
};

export const JOIN_COPY = {
  badge: "Member accounts are coming soon",
  titleLead: "Every 10th protein shake",
  titleHighlight: "is free.",
  lead: "Sign in with your email and every protein shake you buy on your phone earns a stamp. Your 10th protein shake is on us.",
  menuCta: "See the menu",
  buyTodayCta: "How to buy today",
  quickStats: [
    { val: "10th", label: "shake free" },
    { val: "UPI", label: "any app" },
    { val: "Email", label: "sign in" },
  ],
  card: { label: "Stamp card", body: "Your 10th protein shake is on us." },
  expiryChip: { label: "Code expiry", value: "Never" },
  benefitsEyebrow: "Why join",
  benefitsTitleLead: "Buy on your phone.",
  benefitsTitleHighlight: "Earn every time.",
  benefitsLead: "Sign in once with your email. Every protein shake code you buy and every stamp you earn stay in your account.",
  benefits: [
    { icon: "phone", title: "Buy on your phone", body: "Pick a protein shake, pay with any UPI app and get a code to type on the machine.", stat: "UPI", statLabel: "Any app" },
    { icon: "expiry", title: "Codes never expire", body: "Every code you buy is saved in your account and works until you use it.", stat: "0", statLabel: "Expiry dates" },
    { icon: "email", title: "No password", body: "Sign in with a code we email you. There is nothing to remember.", stat: "6", statLabel: "Digit email code" },
  ],
  stepsEyebrow: "Buying today",
  stepsTitleLead: "No account?",
  stepsTitleHighlight: "Buy on the machine.",
  stepsLead: "Every machine takes UPI on its own screen, so you can buy a protein shake right now.",
  steps: SHAKE_STEPS,
  menuLink: "See every protein shake we make",
};

export const SHOP_COPY = {
  title: "Pick your protein shake",
  lead: "Pay with any UPI app. You get a code to type on the machine, and it never expires.",
  online: "Machine online",
  offline: "Machine offline",
  offlineNotice: "This machine is offline right now, so you can't buy here. Try again in a few minutes, or buy on the machine's screen.",
  disabledNotice: "This machine isn't taking orders right now. You can still buy on the machine's screen.",
  emptyMenu: "There's nothing to buy on this machine right now. Check its screen for today's drinks.",
  loadError: "We couldn't load this machine's menu.",
  loadErrorHint: "You can always buy on the machine's screen.",
  retry: "Try again",
  buy: "Buy",
  opening: "Opening payment…",
  soldOut: "Sold out",
  comingSoon: "Coming soon",
  chilled: "Chilled",
  hot: "Hot",
  closedTitle: "Payment not finished",
  closedBody: "You're only charged if you completed the payment. If money left your account, your code is on your order.",
  openOrder: "Open my order",
  checkoutUnavailable: "We couldn't open the payment window. Check your connection and try again.",
  savedTitle: "Your orders on this phone",
  savedOpen: "Open",
  stepsEyebrow: "How it works",
  stepsTitleLead: "Pay on your phone.",
  stepsTitleHighlight: "Type the code.",
  stepsLead: "No account needed. The code works once, at this machine, for the drink you picked.",
  steps: [
    { icon: "phone", title: "Pick and pay", body: "Choose a protein shake here and pay with any UPI app." },
    { icon: "code", title: "Get your code", body: "Your 8-digit code shows up on this page as soon as you've paid." },
    { icon: "tap", title: "Type it on the machine", body: "Tap Get Drinks on the machine's screen and type the code." },
  ],
};

export const RECEIPT_COPY = {
  waitingTitle: "Waiting for your payment",
  waitingBody: "This page updates by itself as soon as your payment comes through. If you closed the payment without paying, you haven't been charged.",
  paidTitle: "Payment received",
  paidBody: "Your code is on its way. This takes a few seconds.",
  slow: "This is taking longer than usual. Keep this page open, or come back to it later. It's saved on this phone.",
  codeTitle: "Your code",
  ready: "Ready to use",
  used: "Used",
  usedBody: "This code has been used on the machine. Enjoy your shake.",
  copy: "Copy code",
  copied: "Copied",
  howTitle: "At the machine",
  howSteps: ["Tap Get Drinks on the screen.", "Type this code.", "Your protein shake is made straight away."],
  rules: "Works once, at this machine, for this drink. It never expires.",
  emailLabel: "Email me this code",
  emailHint: "So you have it even if you close this page.",
  emailSend: "Send",
  emailSending: "Sending…",
  emailSent: (email: string) => `Done. If ${email} is right, the code arrives in a minute or two.`,
  failedTitle: "This order wasn't paid",
  failedBody: "There's no code for it, and you haven't been charged. You can buy again from the menu.",
  refundingTitle: "Refund on its way",
  refundingBody: (price: string) => `We're refunding ${price} to how you paid. Banks usually take 5 to 7 working days.`,
  refundedTitle: "Refunded",
  refundedBody: (price: string) => `${price} has gone back to how you paid.`,
  refundFailedTitle: "We're sorting out your refund",
  refundFailedBody: "Your refund didn't go through the first time. We're on it, and you don't need to do anything.",
  contact: "Contact us",
  notFoundTitle: "We couldn't find that order",
  notFoundBody: "Open the link you got after paying, or go back to the menu.",
  reconnecting: "Checking again…",
  backToMenu: "Back to the menu",
  paidFor: "Paid",
  price: "Price",
};
