const SHAKE_STEPS = [
  { icon: "tap", title: "Pick a protein shake", body: "Tap a protein shake on the machine's screen." },
  { icon: "qr", title: "Pay with UPI", body: "Scan the QR on its pay screen with any UPI app." },
  { icon: "cup", title: "Get your protein shake", body: "The machine makes your protein shake as soon as you've paid." },
];

export const DRINKS_COPY = {
  badge: "Buying on your phone is coming soon",
  titleLead: "Protein shakes",
  titleHighlight: "on the machine.",
  lead: "Soon you'll pick a protein shake here, pay on your phone and get a code to type on the machine. For now, buy on the machine's screen.",
  buyCta: "How to buy",
  menuCta: "See the menu",
  quickStats: [
    { val: "UPI", label: "any app" },
    { val: "60s", label: "blend time" },
    { val: "12", label: "blends" },
  ],
  blendChip: { label: "Blend time", value: "60s" },
  codeChip: { title: "Have a code?", body: "Tap Get Drinks on the machine and type it in." },
  stepsEyebrow: "Buying today",
  stepsTitleLead: "Buy on the machine.",
  stepsTitleHighlight: "Pay with any UPI app.",
  stepsLead: "It takes about a minute and you don't need an account.",
  steps: SHAKE_STEPS,
  codeEyebrow: "Got a code?",
  codeTitleLead: "Type it in.",
  codeTitleHighlight: "No payment needed.",
  codeLead: "If your gym or MuscleBoxPro gave you a code, use it on the machine instead of paying.",
  codeSteps: [
    { icon: "tap", title: "Tap Get Drinks", body: "Find the Get Drinks button on the machine's screen." },
    { icon: "code", title: "Type your code", body: "Enter the code exactly as you got it." },
    { icon: "cup", title: "Get your protein shake", body: "The machine makes your protein shake straight away." },
  ],
  joinTitleLead: "Every 10th protein shake",
  joinTitleHighlight: "is free.",
  joinLead: "Member accounts are coming soon. Sign in with your email and every protein shake you buy on your phone earns a stamp.",
  joinCta: "See how it works",
  menuLink: "See every protein shake we make",
};

export const JOIN_COPY = {
  badge: "Member accounts are coming soon",
  titleLead: "Every 10th protein shake",
  titleHighlight: "is free.",
  lead: "Sign in with your email and every protein shake you buy on your phone earns a stamp. Your 10th protein shake is on us.",
  menuCta: "See the menu",
  buyTodayCta: "How to buy today",
  quickStats: [
    { val: "10th", label: "shake free" },
    { val: "UPI", label: "any app" },
    { val: "Email", label: "sign in" },
  ],
  card: { label: "Stamp card", body: "Your 10th protein shake is on us." },
  expiryChip: { label: "Code expiry", value: "Never" },
  benefitsEyebrow: "Why join",
  benefitsTitleLead: "Buy on your phone.",
  benefitsTitleHighlight: "Earn every time.",
  benefitsLead: "Sign in once with your email. Every protein shake code you buy and every stamp you earn stay in your account.",
  benefits: [
    { icon: "phone", title: "Buy on your phone", body: "Pick a protein shake, pay with any UPI app and get a code to type on the machine.", stat: "UPI", statLabel: "Any app" },
    { icon: "expiry", title: "Codes never expire", body: "Every code you buy is saved in your account and works until you use it.", stat: "0", statLabel: "Expiry dates" },
    { icon: "email", title: "No password", body: "Sign in with a code we email you. There is nothing to remember.", stat: "6", statLabel: "Digit email code" },
  ],
  stepsEyebrow: "Buying today",
  stepsTitleLead: "No account?",
  stepsTitleHighlight: "Buy on the machine.",
  stepsLead: "Every machine takes UPI on its own screen, so you can buy a protein shake right now.",
  steps: SHAKE_STEPS,
  menuLink: "See every protein shake we make",
};
