const SHAKE_STEPS = [
  { icon: "tap", title: "Pick a protein shake", body: "Tap a protein shake on the machine's screen." },
  { icon: "qr", title: "Pay with UPI", body: "Scan the QR on its pay screen with any UPI app." },
  { icon: "cup", title: "Get your protein shake", body: "The machine makes your protein shake as soon as you've paid." },
];

export const DRINKS_COPY = {
  badge: "Buying on your phone is coming soon",
  titleLead: "Protein shakes",
  titleHighlight: "on the machine.",
  lead: "Soon you'll pick a protein shake here, pay on your phone and get a code to type on the machine. For now, buy on the machine's screen.",
  buyCta: "How to buy",
  menuCta: "See the menu",
  quickStats: [
    { val: "UPI", label: "any app" },
    { val: "60s", label: "blend time" },
    { val: "12", label: "blends" },
  ],
  blendChip: { label: "Blend time", value: "60s" },
  codeChip: { title: "Have a code?", body: "Tap Get Drinks on the machine, type it in and tap Submit." },
  stepsEyebrow: "Buying today",
  stepsTitleLead: "Buy on the machine.",
  stepsTitleHighlight: "Pay with any UPI app.",
  stepsLead: "It takes about a minute and you don't need an account.",
  steps: SHAKE_STEPS,
  codeEyebrow: "Got a code?",
  codeTitleLead: "Type it in.",
  codeTitleHighlight: "No payment needed.",
  codeLead: "If your gym or MuscleBoxPro gave you a code, use it on the machine instead of paying.",
  codeSteps: [
    { icon: "tap", title: "Tap Get Drinks", body: "Find the Get Drinks button on the machine's screen." },
    { icon: "code", title: "Type your code", body: 'Type it under "Enter code to start drink" and tap Submit.' },
    { icon: "cup", title: "Get your protein shake", body: "The machine makes your protein shake straight away." },
  ],
  joinTitleLead: "Every 10th protein shake",
  joinTitleHighlight: "is free.",
  joinLead: "Member accounts are coming soon. Sign in with your email and every protein shake you buy on your phone earns a stamp.",
  joinCta: "See how it works",
  menuLink: "See every protein shake we make",
};

export const DRINKS_LIVE_COPY = {
  badge: "Now on your phone",
  titleHighlight: "on your phone.",
  lead: "Scan the QR on a machine's screen to see its protein shakes. Pay by UPI or card, then type your code on the machine.",
  quickStats: [
    { val: "UPI", label: "or card" },
    { val: "60s", label: "blend time" },
    { val: "12", label: "blends" },
  ],
  stepsEyebrow: "How to buy",
  stepsTitleLead: "Scan the machine.",
  stepsTitleHighlight: "Pay on your phone.",
  stepsLead: "It takes about a minute and you don't need an account. You can still pay on the machine's screen with any UPI app.",
  steps: [
    { icon: "qr", title: "Scan the QR", body: 'Tap Get Drinks on the machine, then scan the QR under "Scan to order from your account".' },
    { icon: "phone", title: "Pick and pay", body: "Choose a protein shake and pay by UPI, card or net banking." },
    { icon: "code", title: "Type your code", body: 'Type it under "Enter code to start drink" and tap Submit.' },
  ],
  joinLead: "Sign in with your email and every protein shake you buy on your phone earns a stamp.",
};

export const JOIN_COPY = {
  badge: "Member accounts are coming soon",
  titleLead: "Every 10th protein shake",
  titleHighlight: "is free.",
  lead: "Sign in with your email and every protein shake you buy on your phone earns a stamp. Your 10th protein shake is on us.",
  menuCta: "See the menu",
  buyTodayCta: "How to buy today",
  quickStats: [
    { val: "10th", label: "shake free" },
    { val: "UPI", label: "any app" },
    { val: "Email", label: "sign in" },
  ],
  card: { label: "Stamp card", body: "Your 10th protein shake is on us." },
  expiryChip: { label: "Code expiry", value: "Never" },
  benefitsEyebrow: "Why join",
  benefitsTitleLead: "Buy on your phone.",
  benefitsTitleHighlight: "Earn every time.",
  benefitsLead: "Sign in once with your email. Every protein shake code you buy and every stamp you earn stay in your account.",
  benefits: [
    { icon: "phone", title: "Buy on your phone", body: "Pick a protein shake, pay by UPI or card and get a code to type on the machine.", stat: "UPI", statLabel: "Or card" },
    { icon: "expiry", title: "Codes never expire", body: "Every code you buy is saved in your account and works until you use it.", stat: "0", statLabel: "Expiry dates" },
    { icon: "email", title: "No password", body: "Sign in with a code we email you. There is nothing to remember.", stat: "6", statLabel: "Digit email code" },
  ],
  stepsEyebrow: "Buying today",
  stepsTitleLead: "No account?",
  stepsTitleHighlight: "Buy on the machine.",
  stepsLead: "Every machine takes UPI on its own screen, so you can buy a protein shake right now.",
  steps: SHAKE_STEPS,
  menuLink: "See every protein shake we make",
};

export const MEMBER_COPY = {
  eyebrow: "MuscleBoxPro members",
  titleLead: "Every 10th protein shake",
  titleHighlight: "is free.",
  lead: "Join with your email. Every protein shake you buy on your phone earns a stamp. After 9 stamps, the next one is on us.",
  cardLabel: "Your stamp card",
  cardBody: "9 stamps, then a free protein shake. Any drink, at any machine.",
  benefits: [
    { title: "Your codes kept safe", body: "Every code you buy is saved in your account and never expires." },
    { title: "Orders and refunds", body: "See what you bought, and where a refund is." },
    { title: "No password", body: "We email you a 6-digit code each time you sign in." },
  ],
  formTitle: "Join free",
  formLead: "It takes a minute. Already a member? The same steps sign you in.",
  submit: "Join",
  checking: "Checking your account…",
  guestLead: "Just want a protein shake now?",
  guestCta: "Pay as a guest",
  doneTitle: "You're a member",
  doneBody: "Buy while signed in and every protein shake earns a stamp.",
  doneCta: "Pick a protein shake",
  accountCta: "My account",
  stepsTitle: "How it works",
  steps: [
    { title: "Join with your email", body: "Type the 6-digit code we email you. That's your account." },
    { title: "Buy on your phone", body: "Scan the QR on the machine, pick a protein shake and pay while signed in." },
    { title: "Your 10th is free", body: "After 9 stamps, a free protein shake code shows up in your account." },
  ],
  guestNote: "Bought as a guest and emailed yourself the code? Join with that email and those protein shakes count too.",
};

export const SHOP_COPY = {
  title: "Pick your protein shake",
  lead: "Pay by UPI, card or net banking. You get a code to type on the machine, and it never expires.",
  online: "Machine online",
  offline: "Machine offline",
  offlineNotice: "This machine is offline right now, so you can't buy here. Try again in a few minutes, or buy on the machine's screen.",
  disabledNotice: "This machine isn't taking orders right now. You can still buy on the machine's screen.",
  emptyMenu: "There's nothing to buy on this machine right now. Check its screen for today's drinks.",
  loadError: "We couldn't load this machine's menu.",
  loadErrorHint: "You can always buy on the machine's screen.",
  retry: "Try again",
  buy: "Buy",
  save: (amount: string) => `Save ${amount}`,
  opening: "Opening payment…",
  soldOut: "Sold out",
  comingSoon: "Coming soon",
  chilled: "Chilled",
  hot: "Hot",
  closedTitle: "Payment not finished",
  closedBody: "You're only charged if you completed the payment. If money left your account, your code is on your order.",
  openOrder: "Open my order",
  checkoutUnavailable: "We couldn't open the payment window. Check your connection and try again.",
  savedTitle: "Recent orders",
  savedOpen: "View order",
  savedAll: "All orders",
  machineCode: (sn: string) => `Machine code: ${sn}`,
  memberTitle: "Every 10th protein shake is free",
  memberBody: "Sign in when you pay to collect stamps. Or pay as a guest.",
  memberCta: "Sign in",
  stepsTitle: "How it works",
  stepsLead: "No account needed. The code works once, at this machine, for the drink you picked.",
  steps: [
    { title: "Pick and pay", body: "Choose a protein shake here and pay by UPI, card or net banking." },
    { title: "Get your code", body: "Your 8-digit code shows up on this page as soon as you've paid." },
    { title: "Type it on the machine", body: 'Tap Get Drinks, type it under "Enter code to start drink" and tap Submit.' },
  ],
  machineCaption: "On the machine, tap Get Drinks, then type your 8-digit code under \"Enter code to start drink\" and tap Submit.",
};

export const RECEIPT_COPY = {
  waitingTitle: "Waiting for your payment",
  waitingBody: "This page updates by itself as soon as your payment comes through. If you closed the payment without paying, you haven't been charged.",
  paidTitle: "Payment received",
  paidBody: "Your code is on its way. This takes a few seconds.",
  slow: "This is taking longer than usual. Keep this page open, or come back to it later. It's saved on this phone.",
  codeTitle: "Your code",
  ready: "Ready to use",
  used: "Used",
  usedBody: "This code has been used on the machine. Enjoy your shake.",
  copy: "Copy code",
  copied: "Copied",
  howTitle: "At the machine",
  howSteps: ["Tap Get Drinks on the machine.", 'Type this code under "Enter code to start drink" and tap Submit.', "Your protein shake is made straight away."],
  rules: "Works once, at this machine, for this drink. It never expires.",
  emailLabel: "Email me this code",
  emailHint: "So you have it even if you close this page.",
  emailSend: "Send",
  emailSending: "Sending…",
  emailSent: (email: string) => `Done. If ${email} is right, the code arrives in a minute or two.`,
  failedTitle: "This order wasn't paid",
  failedBody: "There's no code for it, and you haven't been charged. You can buy again from the menu.",
  refundingTitle: "Refund on its way",
  refundingBody: (price: string) => `We're refunding ${price} to how you paid. Banks usually take 5 to 7 working days.`,
  refundedTitle: "Refunded",
  refundedBody: (price: string) => `${price} has gone back to how you paid.`,
  refundFailedTitle: "We're sorting out your refund",
  refundFailedBody: "Your refund didn't go through the first time. We're on it, and you don't need to do anything.",
  contact: "Contact us",
  notFoundTitle: "We couldn't find that order",
  notFoundBody: "Open the link you got after paying, or go back to the menu.",
  reconnecting: "Checking again…",
  backToMenu: "Back to the menu",
  paidFor: "Paid",
  price: "Price",
};

export const PAY_COPY = {
  title: (drink: string) => `Buy ${drink}`,
  guest: "Pay as a guest",
  guestBody: "No account. You get your code on the next page and can email it to yourself.",
  member: "Sign in and pay",
  memberBody: "Your codes are saved in your account, and every 10th protein shake is free.",
  signedInAs: (email: string) => `Signed in as ${email}`,
  pay: (price: string) => `Pay ${price}`,
  cancel: "Cancel",
};

export const SIGNIN_COPY = {
  emailLabel: "Your email",
  emailPlaceholder: "name@example.com",
  sendCode: "Email me a code",
  sending: "Sending…",
  codeLabel: "6-digit code",
  codeSent: (email: string) => `We sent a code to ${email}. It works for 10 minutes.`,
  verify: "Sign in",
  verifyAndPay: (price: string) => `Sign in and pay ${price}`,
  verifying: "Signing in…",
  changeEmail: "Use a different email",
  resend: "Send a new code",
  noPassword: "No password. We email you a code each time.",
  emailMissing: "Enter your email.",
  codeMissing: "Enter the 6-digit code from the email.",
};

export const ACCOUNT_COPY = {
  signInTitle: "Sign in",
  eyebrow: "MuscleBoxPro account",
  heroTitleLead: "Every 10th shake",
  heroBody: "Every protein shake you buy while signed in earns a stamp. After 9, the next one is on us.",
  heroTitleHighlight: "is free.",
  formTitle: "Sign in",
  formLead: "New here? The same steps create your account.",
  perksTitle: "Why sign in",
  perks: [
    { icon: "codes", title: "Codes kept safe", body: "Find every code you bought, on any phone." },
    { icon: "orders", title: "Orders and refunds", body: "See what you bought and where a refund is." },
  ],
  perksJoin: "Emailed yourself a code as a guest? Sign in with that email and those protein shakes join your account, with their stamps.",
  cardLabel: "Stamp card",
  hello: (name: string | null) => (name ? `Hi, ${name}` : "Your account"),
  statsDrinks: "Protein shakes so far",
  statsFree: "Free ones earned",
  readyTitle: "Ready to use",
  readyEmpty: "No codes waiting. Codes you buy while signed in show up here.",
  readyHint: 'On the machine, tap Get Drinks, then type the code under "Enter code to start drink" and tap Submit.',
  usedTitle: (n: number) => `Used codes (${n})`,
  account: "My account",
  signOut: "Sign out",
  stampsTitle: "Stamp card",
  stampsBody: (left: number) => (left === 1 ? "1 more protein shake and the next one is free." : `${left} more protein shakes and the next one is free.`),
  stampsCount: (stamps: number) => `${stamps} of 9`,
  freeReadyCaption: "Free shake ready",
  freeReadyTitle: (n: number) => (n === 1 ? "Your free protein shake is ready." : `${n} free protein shakes are ready.`),
  freeReadyBody: 'Any drink, at any machine. Tap Get Drinks and type it under "Enter code to start drink".',
  freeReadyStamps: (stamps: number) => `You also have ${stamps} of 9 stamps toward the next one.`,
  codesTitle: "My drink codes",
  codesEmpty: "No codes yet. Codes you buy while signed in show up here.",
  freeDrink: "Free protein shake",
  freeDrinkWhere: "Any drink, at any machine",
  ready: "Ready to use",
  used: "Used",
  unknown: "Check on the machine",
  ordersTitle: "My orders",
  ordersEmpty: "No orders yet.",
  more: "Show more",
  loading: "Loading…",
  loadError: "We couldn't load your account. Check your connection and try again.",
  retry: "Try again",
  buyMore: "Buy a protein shake",
  scanHint: "To buy, scan the Get Drinks QR on a machine.",
  deleteTitle: "Delete my account",
  deleteBody: "Your email and name are removed. Codes you haven't used keep working. This can't be undone.",
  deleteConfirm: "Delete my account",
  deleteAsk: "Delete your account?",
  deleted: "Your account is deleted.",
  cancel: "Cancel",
  status: {
    created: "Not paid",
    paid: "Paid, code on its way",
    coded: "Code ready",
    refund_owed: "Refund on its way",
    refunding: "Refund on its way",
    refunded: "Refunded",
    refund_failed: "Refund delayed",
    failed: "Not paid",
  } as Record<string, string>,
};
