/**
 * Commercial terms for the MuscleBox Pro franchise program.
 *
 * Single source of truth for every figure the public /franchise page shows, and the
 * defaults a franchise application is evaluated against. Two rules carry over from
 * `shared/partnership/summary.ts`, for the same reason. A published number is a
 * representation:
 *
 *   1. Nothing in the UI hardcodes a rupee figure, a percentage or a machine count.
 *      Read it from here.
 *   2. This describes the *proposed* program. It is not an offer and it is not the
 *      definitive franchise agreement, which is what binds. The disclaimer the page
 *      renders (§56 of docs/MuscleBox_Pro_Franchise_Program.md) is load-bearing and must
 *      stay visible.
 *
 * Section references are to docs/MuscleBox_Pro_Franchise_Program.md.
 *
 * They used to point at `docs/FranchiseOnboardingPlan.md`, which was an earlier copy of the
 * same document under a name suggesting it was a plan. It has been deleted. The two had
 * diverged: the current document inserts §28, Franchisee Operational Responsibilities, so
 * every reference above 27 shifted by one when they were repointed. If a reference here ever
 * looks off by one against the document, that is the reason.
 */

import { formatInr } from "../partnership/summary";

export type FranchiseTierId = "territory" | "city";

export type FranchiseTier = {
  id: FranchiseTierId;
  /** Full name, as it appears in the agreement. */
  name: string;
  /** Short name for chips, table headers and the tier selector. */
  shortName: string;
  investmentInr: number;
  initialMachines: number;
  /** §1, "Market Rights" column. */
  marketRights: string;
  /** One line on who the tier is for. §2, §3. */
  positioning: string;
  /**
   * The recovery threshold, or `null` where the program does not fix one publicly.
   *
   * §21: the City Franchise threshold is set in the definitive agreement rather than
   * here. `null` is not "no recovery". It is "not published", and the page must say
   * so rather than render a figure or imply the model does not apply.
   */
  capitalRecoveryInr: number | null;
  /**
   * The staged payments, or `null` where the schedule is agreement-specific (§6, City).
   * Percentages, so a change to `investmentInr` cannot leave a stale instalment behind.
   */
  paymentSchedule: { pct: number; trigger: string }[] | null;
  /** §2, §3. Everything the investment includes. */
  includes: string[];
};

export const FRANCHISE_TIERS: readonly FranchiseTier[] = [
  {
    id: "territory",
    name: "MuscleBox Pro Territory Franchise",
    shortName: "Territory Franchise",
    investmentInr: 25_00_000,
    initialMachines: 5,
    marketRights: "A defined geographic territory",
    positioning: "For partners who want to develop a defined geographical territory.",
    capitalRecoveryInr: 25_00_000,
    paymentSchedule: [
      { pct: 50, trigger: "At franchise registration" },
      { pct: 50, trigger: "When machines are ready at the OEM" },
    ],
    includes: [
      "Exclusive rights to develop the assigned territory, subject to performance requirements",
      "Access to the MuscleBox Pro technology platform",
      "Machine monitoring and management",
      "Centralised payment infrastructure",
      "Protein supply pipeline",
      "Machine delivery",
      "Protein delivery to your warehouse",
      "OEM coordination",
      "Technical support",
      "Software and technology updates",
      "Gym leads generated by MuscleBox Pro",
      "Advertising participation",
      "Franchise financial dashboard",
      "Opportunity to expand the number of machines",
    ],
  },
  {
    id: "city",
    name: "MuscleBox Pro City Franchise",
    shortName: "City Franchise",
    investmentInr: 50_00_000,
    initialMachines: 10,
    marketRights: "A defined city",
    positioning:
      "For partners who want responsibility for developing the network across an entire defined city.",
    capitalRecoveryInr: null,
    paymentSchedule: null,
    includes: [
      "Exclusive city-level development rights, subject to performance requirements",
      "Access to the complete MuscleBox Pro technology ecosystem",
      "Machine monitoring and management",
      "Centralised payment infrastructure",
      "Protein supply pipeline",
      "Machine delivery",
      "Protein delivery to your warehouse",
      "OEM coordination",
      "Technical support",
      "Software and technology updates",
      "Gym leads generated by MuscleBox Pro",
      "Advertising participation",
      "Franchise financial dashboard",
      "Priority consideration for additional machines and expansion",
    ],
  },
];

export function franchiseTier(id: FranchiseTierId): FranchiseTier {
  const tier = FRANCHISE_TIERS.find((t) => t.id === id);
  if (!tier) throw new Error(`Unknown franchise tier: ${id}`);
  return tier;
}

/**
 * The tiers' `includes` lists split into what both carry and what is specific to one.
 *
 * Derived rather than authored, so the two lists above stay the single description of
 * each tier. Eleven of the fourteen entries are common, and printing both lists in full
 * side by side asks the reader to diff them to find the three lines that differ.
 */
export function tierIncludes(): {
  shared: string[];
  unique: Record<FranchiseTierId, string[]>;
} {
  const [first, ...rest] = FRANCHISE_TIERS;
  const shared = first.includes.filter((item) =>
    rest.every((tier) => tier.includes.includes(item)),
  );
  const unique = Object.fromEntries(
    FRANCHISE_TIERS.map((tier) => [tier.id, tier.includes.filter((i) => !shared.includes(i))]),
  ) as Record<FranchiseTierId, string[]>;
  return { shared, unique };
}

export const FRANCHISE = {
  /**
   * §17, §19. The protein-business split, before and after capital recovery.
   *
   * 100% during recovery is a *capital recovery mechanism*, not a margin. It is how
   * the franchisee gets the investment back, and the page must not present it as a
   * permanent share.
   */
  proteinProfitSharePct: { duringRecovery: 100, afterRecovery: 50 },

  /**
   * §18, §42. Advertising is permanent and it never counts toward capital recovery.
   * That separation is the single most misread term in the program, so it is stated
   * on the split itself rather than only in prose.
   */
  advertising: {
    franchiseeSharePct: 25,
    mbpSharePct: 75,
    countsTowardRecovery: false,
  },

  /** §15. What comes off gross revenue before the *gym's* share is worked out. */
  gymLevelCosts: ["Protein cost", "Cup and consumable cost"],

  /**
   * §16. What comes off before the *franchise* share is worked out. Longer than the
   * gym list on purpose, and the difference is the point: franchise profit is
   * calculated on the real economics of running a local network.
   */
  franchiseLevelCosts: [
    "Protein cost",
    "Cup and consumable cost",
    "Transportation",
    "Warehousing",
    "Loading and unloading",
    "Machine movement",
    "Payment processing charges",
    "Direct operational expenses",
    "Product wastage or spoilage",
    "Other directly attributable operating costs",
  ],

  /** §11. Examples only. MuscleBox Pro sets the applicable split per location. */
  gymProfitSharingExamples: ["80:20", "50:50"],

  /**
   * The vintage of every term above, rendered in the /franchise disclaimer and emitted as
   * `dateModified` in the page's WebPage schema.
   *
   * Here rather than typed into that sentence so that revising the program and revising
   * the quarter it is "as of" are one edit. An undated set of rupee figures is an
   * open-ended representation about money, and rule 2 at the top of this file is the
   * reason the page can publish them at all.
   */
  asOf: "Q3 2026",
} as const;

/**
 * §8. Ownership, as two lists.
 *
 * Kept apart rather than merged because a tick beside "cannot sell a machine" reads
 * as a benefit. The franchise buys an operating right, not a machine, and the page
 * has to be unambiguous about that before anyone pays.
 */
export const MACHINE_RIGHTS = {
  may: [
    "Operate assigned machines at approved gym locations",
    "Move machines between approved locations",
    "Replace an underperforming gym",
    "Coordinate local machine deployment",
  ],
  mayNot: [
    "Sell a machine or transfer machine ownership",
    "Independently commercialise a machine",
    "Use a machine outside the MuscleBox Pro ecosystem",
    "Modify or reverse engineer the machine",
    "Remove MuscleBox Pro technology or branding",
    "Use a machine for a competing business",
  ],
} as const;

/** §9, §24, §26, §27, §29. Who does what, once the machines land. */
export const RESPONSIBILITIES = {
  mbp: [
    "The machines, built and delivered",
    "Protein, brought to your warehouse",
    "Software and updates",
    "Payment collection and payouts",
    "Recipes and shake prices",
    "Gym leads and the standard gym deal",
    "Repairs, diagnostics and warranty",
    "Final say on every gym",
  ],
  franchisee: [
    "A warehouse, kept in the right conditions",
    "Local transport and machine moves",
    "Stock, once it reaches you",
    "Finding and pitching gyms",
    "Day-to-day gym relationships",
    "Your own team on the ground",
    "Meeting your targets",
    "Following the brand and operating rules",
  ],
} as const;

/**
 * §28. The upkeep loop at each machine, once deployed.
 *
 * Everything here is downstream of the warehouse. Storage conditions, local transport
 * and gym coordination are stated in `RESPONSIBILITIES.franchisee` and must not be
 * repeated here, or the page says the same duty twice in two voices.
 */
export const MACHINE_UPKEEP = [
  "Check each machine is working",
  "Top up protein before it runs out",
  "Refill cups and other approved supplies",
  "Pull anything past its expiry date",
  "Keep the machine and its area clean",
  "Act on alerts from the platform",
  "Tell us about faults quickly",
] as const;

/** §22. What the franchise dashboard shows. */
export const DASHBOARD_VISIBILITY = [
  "Machine-wise sales and shake volume",
  "Gross revenue",
  "Protein and cup consumption",
  "Gym share",
  "Transportation, warehouse and other operating costs",
  "Advertising income",
  "Franchise distributable profit and payouts",
  "Capital recovery progress and remaining amount",
  "Machine status and operational alerts",
] as const;

/** §31. What territorial exclusivity is conditional on (§4). */
export const PERFORMANCE_REQUIREMENTS = [
  "Minimum number of machines deployed",
  "Deployment deadlines",
  "Minimum active-machine requirements",
  "Minimum territory development",
  "Timely replacement of non-performing locations",
  "Operational compliance with MuscleBox Pro standards",
] as const;

/** §5. Carved out of exclusivity, and better said early than discovered later. */
export const RESERVED_ACCOUNTS = [
  "National gym chains",
  "Strategic corporate partnerships",
  "National and large institutional accounts",
  "National advertising partnerships",
  "Partnerships negotiated directly by MuscleBox Pro",
] as const;

/**
 * §52. Application through to the long-term partnership.
 *
 * `phase` groups the eleven steps into the four stages of `JOURNEY_PHASES`. Eleven
 * equally-weighted steps read as a list to get through; four stages read as a process,
 * and the stage boundaries are where the commitment actually changes.
 */
export const FRANCHISE_JOURNEY = [
  {
    phase: "approve",
    title: "Apply",
    body: "Submit an application for the territory or city you want to develop.",
  },
  {
    phase: "approve",
    title: "Market evaluation",
    body: "We assess market potential, gym density, existing locations and territory capacity.",
  },
  {
    phase: "approve",
    title: "Franchise approval",
    body: "The tier and the territory are finalised together.",
  },
  {
    phase: "approve",
    title: "Agreement",
    body: "The definitive franchise agreement is executed.",
  },
  {
    phase: "fund",
    title: "Initial payment",
    body: "The first-stage investment is paid at registration.",
  },
  {
    phase: "fund",
    title: "Machine procurement",
    body: "We place the OEM order and you get procurement and manufacturing updates.",
  },
  {
    phase: "fund",
    title: "Machine readiness",
    body: "The second-stage investment is paid once machines are ready at the OEM.",
  },
  {
    phase: "deploy",
    title: "Deployment",
    body: "Machines are delivered and installed at approved gym locations.",
  },
  {
    phase: "deploy",
    title: "Network operation",
    body: "You develop and run the local network with us.",
  },
  {
    phase: "grow",
    title: "Capital recovery",
    body: "You receive 100% of eligible protein-business distributable profit until the recovery threshold is met.",
  },
  {
    phase: "grow",
    title: "Long-term partnership",
    body: "Protein profit moves to 50:50. Advertising stays at 25:75.",
  },
] as const;

export type FranchiseJourneyPhaseId = (typeof FRANCHISE_JOURNEY)[number]["phase"];

export const JOURNEY_PHASES: readonly { id: FranchiseJourneyPhaseId; title: string }[] = [
  { id: "approve", title: "Apply and get approved" },
  { id: "fund", title: "Fund and procure" },
  { id: "deploy", title: "Deploy and operate" },
  { id: "grow", title: "Recover and grow" },
];

/**
 * The journey grouped for rendering, with each step keeping its position in the full
 * eleven so the numbering on the page matches the order in §52.
 */
export function journeyByPhase() {
  return JOURNEY_PHASES.map((phase) => ({
    ...phase,
    steps: FRANCHISE_JOURNEY.map((step, index) => ({ ...step, position: index + 1 })).filter(
      (step) => step.phase === phase.id,
    ),
  }));
}

/**
 * §20's worked illustration, computed rather than transcribed.
 *
 * The point it exists to make is arithmetical: advertising income received during
 * recovery does not reduce the remaining amount, and profit that arrives *past* the
 * threshold is split rather than paid out whole. Both were wrong in every hand-written
 * version of this example, in opposite directions.
 */
export function recoveryExample(tierId: FranchiseTierId = "territory") {
  const tier = franchiseTier(tierId);
  const threshold = tier.capitalRecoveryInr;
  if (threshold === null) {
    throw new Error(`No published capital recovery threshold for tier: ${tierId}`);
  }

  const alreadyReceivedInr = 20_00_000;
  const nextDistributionInr = 8_00_000;

  const remainingInr = threshold - alreadyReceivedInr;
  const completesRecoveryInr = Math.min(nextDistributionInr, remainingInr);
  const postRecoveryPoolInr = nextDistributionInr - completesRecoveryInr;
  const postRecoveryToFranchiseeInr = Math.round(
    (postRecoveryPoolInr * FRANCHISE.proteinProfitSharePct.afterRecovery) / 100,
  );

  return {
    thresholdInr: threshold,
    alreadyReceivedInr,
    remainingInr,
    nextDistributionInr,
    completesRecoveryInr,
    postRecoveryPoolInr,
    postRecoveryToFranchiseeInr,
    /**
     * The remainder of the pool, and the whole distribution's total to the franchisee.
     * Derived here rather than in the page so the illustration's three parts always sum
     * to `nextDistributionInr`. Subtracting in JSX is where a rounded half goes missing.
     */
    postRecoveryToMbpInr: postRecoveryPoolInr - postRecoveryToFranchiseeInr,
    totalToFranchiseeInr: completesRecoveryInr + postRecoveryToFranchiseeInr,
    /** Fraction recovered so far, for the progress bar. 0–1. */
    progress: alreadyReceivedInr / threshold,
  };
}

/**
 * The headline form, "₹25 Lakh". `formatInr` gives "₹25,00,000", which is the right
 * thing in a table and eight characters of noise in a 48px display heading.
 *
 * Falls back to `formatInr` below one lakh and for anything that is not a whole
 * number of lakhs, rather than rendering "₹2.5 Lakh" for ₹2,50,000 in a heading sized
 * for two digits.
 */
export function formatLakh(amountInr: number): string {
  const lakhs = amountInr / 1_00_000;
  if (amountInr < 1_00_000 || !Number.isInteger(lakhs)) return formatInr(amountInr);
  return `₹${lakhs} Lakh`;
}

export { formatInr };
